bash-it enable plugin base
bash-it enable plugin browser
bash-it enable plugin dirs
bash-it enable plugin extract
bash-it enable plugin fasd
bash-it enable plugin git
bash-it enable plugin java
bash-it enable plugin osx
bash-it enable plugin python
bash-it enable plugin ssh
bash-it enable plugin tmux
bash-it enable plugin tmuxinator
bash-it enable plugin virtualenv
